# Use an official Python runtime as a parent image
FROM python:3.8.5-slim

RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc wget vim curl

# Configure Datetime
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY requirements.txt /app/requirements.txt
COPY ./ /app/code

# Install any needed packages specified in requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt

EXPOSE 
    ################################
    ####### Incluir código #########
    ################################

################################
####### Incluir código #########
################################
